spring:
  application:
    name: loans-service
  datasource:
    username: sa
    url: jdbc:h2:mem:loans_service
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9005
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
