spring:
  application:
    name: loans
  datasource:
    username: sa
    url: jdbc:h2:mem:loans_service
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:9001/"
  profiles:
    active: "prod"
server:
  port: 9005
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true


