spring:
  application:
    name: cards-service
  datasource:
    username: sa
    url: jdbc:h2:mem:cards_service
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9004
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
