spring:
  application:
    name: cards
  datasource:
    username: sa
    url: jdbc:h2:mem:cards_service
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:9001/"
  profiles:
    active: "prod"
server:
  port: 9004
management:
  endpoints:
    web:
      exposure:
        include: '*'


