spring:
  application:
    name: accounts-service
  datasource:
    username: sa
    url: jdbc:h2:mem:accounts_service
    password:
  h2:
    console:
      enabled: true

server:
  port: 9003
    
management:
  endpoints:
    web:
      exposure:
        include: '*'