eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9002
spring:
  application:
    name: eureka-server
