management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          force-pull: true
          timeout: 100
          uri: https://github.com/anandlshinde/sbms-config
          clone-on-start: true
  profiles:
    active: git
